# Generated by Django 4.0.4 on 2022-07-22 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 22, 11, 29, 40, 85001, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
