# Generated by Django 4.0.4 on 2022-07-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_task_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
